### ISSUE TITLE
my BuildGuide does not Save Shapes!

### ISSUE THREAD

**Issue by XWutz** [brentmaas/BuildGuide#1]
Hello

I think it is not intended so I enter here because my BuildGuide does not save shapes I've done with it!

PLS, help!

THX
Patrick

**Comment by brentmaas** [comment]
Hi Patrick,

Sorry for taking a while to respond.

Could you specify in what way you want to save shapes? Do you use the latest version of the mod (0.4.0 currently)?

If you mean that changing the parameters of a shape in game doesn't affect the shape; do the '-' and '+' buttons work? Do you press the 'Set' button after typing in a number?

If you mean that the shapes are gone when you open another world or log into another server; this is intended and I still plan to add a way to transfer shapes between these different sessions. The shapes should still be there when you open the world or log into the server where you created them.

If you mean that the shapes are gone when you completely restart the game; this is also intended in the sense that the mod currently does everything in memory. I also still plan to add these persistent sessions at some point.

If these situations are not what you meant or didn't help, please describe further what you are trying to do or what you want the mod to do. A [pastebin.com](https://pastebin.com/) link with your debug.log might also help in certain situations.

**Comment by XWutz** [comment]
Hello

Thx for Answering first! ^^ 

It is that the Shape/s where gone after restarting the game. But if its Memory-based then its normal i guess! ^^

Being able to make them persistent would be great! Even when it would just work in 1 World! Having a way to use them on different worlds like importing a schematic would be enormously greater! ;-)

I Love that Mod, GREAT WORK, thumbs up!!!!!

**Comment by brentmaas** [comment]
Hi, you're welcome and thank you for the compliments :)! Good to know that it's within the current expected behaviour as well.

I'll keep the issue open since it's technically something that still has to be implemented. Life has been a bit busy, but I hope to resume development again soon-ish.

**Comment by brentmaas** [comment]
Hi Patrick! It's been a while, but shapes can now be automatically saved to a file and automatically restored when the game is reloaded. It's currently disabled by default, but you can enable it in the config.
