### ISSUE TITLE
Center origin option for cuboid

### ISSUE THREAD

**Issue by Notarin** [brentmaas/BuildGuide#6]
A toggle to set the origin of the cuboid as the center of it would be great, so that I may know the center point and just specify the dimensions.
Most other shapes the center point is already the origin, however the origin point of the cuboid is currently the corner, having an option/toggle to have it be the center would be great

**Comment by brentmaas** [comment]
Yeah, I should be able to do that. I need to release a hotfix later today, so I'll try to get it in that.

**Comment by Notarin** [comment]
That is absolutely fantastic, the mod will be perfect for me when you do thank you very much

**Comment by brentmaas** [comment]
Implemented in d6c07c83ab5344f8bc625ff6eee89736e1f4c237 and should be released now!

**Comment by Notarin** [comment]
Amazing, thank you!!! This makes this perfect for me.
