### ISSUE TITLE
Crash with Caxton

### ISSUE THREAD

**Issue by notrohit1702** [brentmaas/BuildGuide#8]
When [Caxton](https://modrinth.com/mod/caxton) and [Build Guide](https://modrinth.com/mod/build-guide) are installed together, it causes a crash ([log](https://mclo.gs/Mda8avf)). I'm guessing that this isn't easily fixable, so I would like to request that it be marked as incompatible for convenience of debugging.

**Comment by brentmaas** [comment]
It looks like something is going wrong while starting the game in a function that Caxton modifies. I don't think the function is really meant to be called while the game is starting, but it worked fine when the function is unmodified and it saved me some effort working around it. [I've opened an issue on Caxton's repository](https://gitlab.com/Kyarei/caxton/-/issues/84) and I'll let you know what happens to it. I could probably rewrite a part to work around it if they don't think it's worth fixing.

**Comment by brentmaas** [comment]
Caxton's author is incredibly quick and has already fixed it. It should be included in the upcoming 0.6.0-alpha.4 release of Caxton.
